use configMap and envFrom to specify kv pairs in env

diff --git a/src/MissionParallelCatchup/parallel_catchup_helm/templates/job_preload_redis.yaml b/src/MissionParallelCatchup/parallel_catchup_helm/templates/job_preload_redis.yaml
--- a/src/MissionParallelCatchup/parallel_catchup_helm/templates/job_preload_redis.yaml
+++ b/src/MissionParallelCatchup/parallel_catchup_helm/templates/job_preload_redis.yaml
@@ -11,28 +11,20 @@ spec:
         command: ["/bin/sh", "-c"]
         args: 
          - |-
-           if [ \"$STRATEGY\" = \"uniform\" ]; then 
-             /bin/sh /scripts/uniform_range_generator.sh
-           elif [ \"$STRATEGY\" = \"logarithmic\" ]; then 
-             /bin/sh /scripts/logarithmic_range_generator.sh
-           else 
-             echo 'Error: Unknown strategy' && exit 1
-           fi
-        env:
-        - name: STRATEGY
-          value: "{{ .Values.range_generator.strategy }}"
-        - name: STARTING_LEDGER
-          value: "{{ .Values.range_generator.params.starting_ledger }}"
-        - name: LATEST_LEDGER_NUM
-          value: "{{ .Values.range_generator.params.latest_ledger_num }}"
-        - name: OVERLAP_LEDGERS
-          value: "{{ .Values.range_generator.params.overlap_ledgers }}"
-        - name: LEDGERS_PER_JOB
-          value: "{{ .Values.range_generator.params.uniform_ledgers_per_job }}"
-        - name: LOGARITHMIC_FLOOR_LEDGERS
-          value: "{{ .Values.range_generator.params.logarithmic_floor_ledgers }}"
-        - name: NUM_PARALLELISM
-          value: "128"
+           case "$STRATEGY" in
+             "uniform")
+               /bin/sh /scripts/uniform_range_generator.sh
+               ;;
+             "logarithmic")
+               /bin/sh /scripts/logarithmic_range_generator.sh
+               ;;
+             *)
+               echo 'Error: Unknown strategy' && exit 1
+               ;;
+           esac
+        envFrom:
+        - configMapRef:
+            name: range-generator-config
         volumeMounts:
         - name: script
           mountPath: /scripts
@@ -55,3 +47,16 @@ data:
     {{- (.Files.Get "files/uniform_range_generator.sh") | nindent 4 }}
   logarithmic_range_generator.sh: |-
     {{- (.Files.Get "files/logarithmic_range_generator.sh") | nindent 4 }}
+---
+apiVersion: v1
+kind: ConfigMap
+metadata:
+  name: range-generator-config
+data:
+  STRATEGY: "{{ .Values.range_generator.strategy }}"
+  STARTING_LEDGER: "{{ .Values.range_generator.params.starting_ledger }}"
+  LATEST_LEDGER_NUM: "{{ .Values.range_generator.params.latest_ledger_num }}"
+  OVERLAP_LEDGERS: "{{ .Values.range_generator.params.overlap_ledgers }}"
+  LEDGERS_PER_JOB: "{{ .Values.range_generator.params.uniform_ledgers_per_job }}"
+  LOGARITHMIC_FLOOR_LEDGERS: "{{ .Values.range_generator.params.logarithmic_floor_ledgers }}"
+  NUM_PARALLELISM: "128"
